packages:
  - packages/*

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@qualcomm-ui/core@1.11.8'
  - '@qualcomm-ui/dom@1.1.6'
  - '@qualcomm-ui/qds-core@1.35.1'
  - '@qualcomm-ui/react-core@1.5.10'
  - '@qualcomm-ui/react@1.27.5'
  - '@qualcomm-ui/utils@1.3.3'

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - unrs-resolver
