packages:
  - packages/*

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  unrs-resolver: true

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - unrs-resolver
